### ISSUE TITLE
Unable to get my personal access token

### ISSUE THREAD

**Issue by oscarvarto** [ProtonVPN/proton-vpn-gtk-app#1]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x ] I have searched open and closed issues for duplicates
- [x ] This isn't a feature request
- [x ] This is not a report about my app not working as expected

I tried to follow instructions at https://github.com/ProtonVPN/proton-vpn-gtk-app#proton-package-registry but I am unable to reach
https://gitlab.protontech.ch/help/user/profile/personal_access_tokens.md
(seems to be a broken link)

I cannot reach https://gitlab.protontech.ch/
Has this link changed?

The reason I am trying to build the VPN GTK app is because it seems protonvpn from AUR is outdated. I cannot find a tarball, deb, rpm package to install the VPN.

Honestly, it's a pain to deal with installation issues and your web page https://protonvpn.com/download-linux is not user friendly at all. It only takes you from on link to another and goes back in circles. The AUR package is outdated right now, as far as I understand.

At least provide a correct way to install the programs from source. I'm a paying subscriber and this is making me regret my choice.

----------------------------------------

**Comment by calexandru2018** [comment]
Hey @oscarvarto those are mainly internal instructions. If you'd like to build it manually you'd do as any other python package, download the repo and install it in a venv. As of the moment I won't be pushing to AUR as there are still things that we need to improve and we can't spread thinly through all the distros.

The KBs on https://protonvpn.com/download-linux will be soon refactored to reflect all of these changes.

**Comment by robert-e-davidson3** [comment]
For what it's worth in terms of priority, I found myself here for exactly the same reason as Oscar.

**Comment by paerbac** [comment]
@calexandru2018 doesn't it kind of go against the spirit of the GPL-3.0 license to have a roadblock like this that prevents the community from compiling themselves?

**Comment by molaeiali** [comment]
@oscarvarto I managed to install it on Arch and put it on AUR: https://aur.archlinux.org/packages/proton-vpn-gtk-app
