### ISSUE TITLE
GTK App killswitch doesn't prevent non-VPN connections

### ISSUE THREAD

**Issue by hbloeht** [ProtonVPN/proton-vpn-gtk-app#10]
If killswitch is enabled, closing the app doesn't prevent non-VPN connections. The old app had this feature.

**Comment by Biepa** [comment]
Can confirm this.

**Comment by xcpn** [comment]
> If killswitch is enabled, closing the app doesn't prevent non-VPN connections. The old app had this feature.
> 

There's just a Kill-Switch and then there is a Permanent Kill-Switch, the old app had both.

The new app has yet to implement the Permanent Kill-Switch and I'm wondering when it'll be done. I have put the the old app on update-hold because I'm not willing to use it without a Permanent Kill-Switch.

**Comment by caerulescens** [comment]
I noticed this as well, and I can confirm this. I'm doing the same as @xcpn w.r.t. the old app.

**Comment by daqnal** [comment]
Can confirm, and I +1 the permanent kill-switch feature req. I'd bet it's actually used more often than the temporary kill-switch.

**Comment by calexandru2018** [comment]
This has been added to the beta version, follow this link on how to give it a spin as we need as much people as possible to test this: https://protonvpn.com/support/linux-prerelease/

**Comment by BIGBEASTISHANK** [comment]
> This has been added to the beta version, follow this link on how to give it a spin as we need as much people as possible to test this: https://protonvpn.com/support/linux-prerelease/
> 
> edit: once you've installed the beta version check the release notes ;)

Bro please see my issue too it's a headache to solve it #33

**Comment by Anonymous941** [comment]
> This has been added to the beta version, follow this link on how to give it a spin as we need as much people as possible to test this: https://protonvpn.com/support/linux-prerelease/
> 
> edit: once you've installed the beta version check the release notes ;)

@calexandru2018 Thank you, I really appreciate you adding this! :)

**Comment by BIGBEASTISHANK** [comment]
> This has been added to the beta version, follow this link on how to give it a spin as we need as much people as possible to test this: https://protonvpn.com/support/linux-prerelease/
> 
> edit: once you've installed the beta version check the release notes ;)

How can i get it on arch??

**Comment by calexandru2018** [comment]
This has been released to all stable clients with v4.2.0
