### ISSUE TITLE
Failed to check proton-vpn-gtk-app dependencies

### ISSUE THREAD

**Issue by anwaruddin2k** [ProtonVPN/proton-vpn-gtk-app#11]
os manjaro gnome 
I am using pamac but it does not proceed with installation.
![2023-11-17_22-53](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/53415502/6bd4f030-8aae-47a0-9472-4ccf1415d424)

**Comment by Weilbyte** [comment]
Not an official package; but are you having no issues building any other packages on your system?

**Comment by anwaruddin2k** [comment]
> Not an official package; but are you having no issues building any other packages on your system?

Yes all other apps are installing fine.

**Comment by Anonymous941** [comment]
Try running it in the terminal to get a more detailed error

**Comment by Weilbyte** [comment]
Also try with another AUR helper, such as `yay`.

**Comment by anwaruddin2k** [comment]
its working now . thanks for your response .
