### ISSUE TITLE
Not able to Login in linux client on kali kde plasma

### ISSUE THREAD

**Issue by Aviksaikat** [ProtonVPN/proton-vpn-gtk-app#21]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
I have contacted the support & posted on reddit as well. The desktop client is not running on `kali 2023.4 kde plasma`. I have used it in the past on kali for several years but recently I'm trying to install on my new machine & the gtk client is not logging in. When I enter my creds I see a notification in my phone about a new login but then it's stuck in the login screen.

Here is the reddit issue where I have put my logs 
& also I have emailed the support with logs as well https://www.reddit.com/r/ProtonVPN/comments/18q295y/desktop_client_stuck_at_login_loop_on_kali_linux/

**Comment by calexandru2018** [comment]
Hey @Aviksaikat 

Hope at this point things somehow got solved, but honestly can't help much here as we currently don't support this distro.
