### ISSUE TITLE
Wireguard Technical Questions

### ISSUE THREAD

**Issue by funkemunky** [ProtonVPN/proton-vpn-gtk-app#22]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
What is the status of Wireguard implementation and where are the roadblocks? If there is a timeline page for it, I have not found it.

My main concern is that the GTK app for ProtonVPN already utilizes the OpenVPN structure built into Linux. Why is the Wireguard implementation within Linux not being used as well?

I just want to know how I can potentially contribute.

**Comment by Cherkah** [comment]
that's true ! why can i chose wireguard protocol in the GTK app? the app is new maybe we  have to wait and (hope) see

**Comment by calexandru2018** [comment]
We'll be working on WG once we bring in all features from previous client to current one and work a bit more on stability.
