### ISSUE TITLE
Popup is not 

### ISSUE THREAD

**Issue by xbz-24** [ProtonVPN/proton-vpn-gtk-app#23]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
![image](https://github.com/ProtonVPN/proton-vpn-gtk-app/assets/68678258/3ed68ca0-b093-4537-88fe-984756438d9b)

Why do I get this popup?

Nothing of my proton credentials seem to satisfy this

**Comment by BIGBEASTISHANK** [comment]
go to [https://account.protonvpn.com/login](https://account.protonvpn.com/login) then go to account copy your openvpn username and pass and then enter it here

**Comment by calexandru2018** [comment]
Seems related to https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/30 thus closing this ticket.
