### ISSUE TITLE
Auto select protocol should be more humanity for client

### ISSUE THREAD

**Issue by mkevinstever** [ProtonVPN/proton-vpn-gtk-app#24]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Once detected proton main site API blocked. should trying to connect stealth protocol first. on the most network restrictive environment. other VPN protocol almost unable to use.
Might you know, users can not wait connect for long time, right?

**Comment by calexandru2018** [comment]
We'll work on that once we reach to a point where the app will allows to expand into those areas, it's our goal to reach feature parity with other platforms but currently we need to focus on stability, bringing in WG and CLI.
