### ISSUE TITLE
Why isn't the ProtonVPN on flathub verified?

### ISSUE THREAD

**Issue by Mr-Bajs** [ProtonVPN/proton-vpn-gtk-app#27]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ ] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

Alot of apps on flathub are now being verified by their developers since Flathub introduces verification. ProtonVPN aren't verified. Why isn't it?

**Comment by calexandru2018** [comment]
Because we don't have the bandwidth to currently verify the apps. Once we get another dev we might look into it, but as it now we can't stretch ourselves too thin as we really want to make the linux app great!
