### ISSUE TITLE
How can I install this new app in fedora 39 ?

### ISSUE THREAD

**Issue by andirsun** [ProtonVPN/proton-vpn-gtk-app#3]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

**Comment by Weilbyte** [comment]
Doesn't appear to be supported yet.

**Comment by andirsun** [comment]
@proletarius101 Yes but I think flatpak app is based on the old [app](https://github.com/ProtonVPN/linux-app)

**Comment by andirsun** [comment]
Update: Flatpak is based in this repo.

**Comment by iMonZ** [comment]
> You can try the unofficial Flatpak repackaging of the official ProtonVPN: https://flathub.org/apps/com.protonvpn.www

That's actually the best way
