### ISSUE TITLE
Please fix these basic and extremely annoying issues (probably just need to stop using gnome keyring/kwallet)

### ISSUE THREAD

**Issue by NigoriousT** [ProtonVPN/proton-vpn-gtk-app#35]
The app wants to create a new keyring called "Default" each time I start my computer. In addition, the app never saves my login after it closes.

These issues happen to me on clean installs of:
- Ubuntu
- Kubuntu
- Debian Gnome
- Debian KDE

I don't know if you all didn't bother testing the application or i'm just really unlucky but please just store the information for the application somewhere in the home folder. Windscribe does this and as a result it works perfectly on every distribution and desktop environment. These keyrings have had random issues like this reported constantly over the last 10 years and the solution that works 100% of the time is to simply not use them.

**Comment by Anonymous941** [comment]
I've been trying to get this issue fixed too for forever.  Happens on all of my computers, some are GNOME with GNOME keyring, and some are KWallet.  Here are some other issues about this (all unresolved, and there are probably more): #30 #16 #8

**Comment by BIGBEASTISHANK** [comment]
> KWallet

You all can use proton on kwallet?? it is my (using bspwm on arch) problem that kwallet is fucking slow and can only open after 2 minute of user login?? I have to installl gnome keyring to fix that issue, headache man

**Comment by calexandru2018** [comment]
Hey all, could you please send issue reports through the app so we have some logs on this please ? I talked internally to our QA and we're a bit unsure why this is happening with gnome backend, it is expected with KDE as kwallet is a bit more tricky. Please refer to this ticket in the submission.

**Comment by mohammedthejihadist** [comment]
I had this happen to me too back when I was using Ubuntu 22.04. I remember steps I took for install:

1. Install Ubuntu 22.04, encrypted LVM, minimal install, auto signin on
2. Install ProtonVPN as instructed on website normally, optional system icon tray does not make a difference
3. When it asks you to create a keyring password the first time, I made it blank
4. Watch the application never save your password and make a popup each time you start computer

I cant send logs cause im using Arch btw right now but I hope this can help anyway.

**Comment by NigoriousT** [comment]
I have done some more testing, Ubuntu 22.04 full bloated installation and Ubuntu 23.10 the issue still happens. But on Fedora Workstation the VPN works perfectly.

Also I don't know how it's related to the original issues I mentioned, but the auto connect on startup also only works on Fedora Workstation and not Ubuntu or Debian.

**Comment by BIGBEASTISHANK** [comment]
hi

-------- Original Message --------

**Comment by calexandru2018** [comment]
Closing this and any further discussions should be on https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/30
