### ISSUE TITLE
Instructions or a way to install the app on unsupported linux distribution

### ISSUE THREAD

**Issue by vysdel** [ProtonVPN/proton-vpn-gtk-app#39]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ x ] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [ x ] This is not a report about my app not working as expected

----------------------------------------

Please provide a way to use the official app package in case of unsupported linux distributions. 
This is especially important now that you have deprecated protonvpn-cli and it no longer works at all  https://github.com/Rafficer/linux-cli-community/issues/365

Maybe you can provide instructions on how to install it into virtual env with pip? Or even you can create official releases with AppImage or Flatpak which wok on any distro?

Thanks

**Comment by calexandru2018** [comment]
Hey @vysdel , so this is a bit of a complicated topic.

We want to support as much as possible, but if we'd introduce manual installations we'd overwhelm ourselves with distributions that we do not support, and thus loose focus on what has to be done. We'll provide official manual  installations as soon as our app gets a bit on par with the other platforms, until then I can leave some instructions here that you can try by yourself. Note that this is not officially supported so do at your own risk:

Install the packages in the following order and make sure you're doing it inside a venv:
- https://github.com/ProtonVPN/python-proton-core
- https://github.com/ProtonVPN/python-proton-vpn-logger
- https://github.com/ProtonVPN/python-proton-vpn-killswitch
- https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager
- https://github.com/ProtonVPN/python-proton-vpn-connection
- https://github.com/ProtonVPN/python-proton-vpn-network-manager
- https://github.com/ProtonVPN/python-proton-vpn-network-manager-openvpn
- https://github.com/ProtonVPN/python-proton-keyring-linux
-
