### ISSUE TITLE
Consider using a monorepo for all python-proton-vpn-* packages

### ISSUE THREAD

**Issue by ranile** [ProtonVPN/proton-vpn-gtk-app#47]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

The README states:

> ### Virtual environment
> 
> If you didn't do it yet, to be able to pip install Proton VPN components you'll need to set up our internal Python package registry. You can do so running the command below, after replacing `{GITLAB_TOKEN`} with your [personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) with the scope set to `api`.
> 
> ```shell
> pip config set global.index-url https://__token__:{GITLAB_TOKEN}@{GITLAB_INSTANCE}/api/v4/groups/{GROUP_ID}/-/packages/pypi/simple
> ```

This makes the job of using running the app from the source code extremely difficult. Moreover, the README also doesn't mention what GitLab instance to use, which makes me think that the instance being used is https://gitlab.com/, a 3rd party service.

I bring this up as I would like an easy way to build/run the app from source without needing to clone a bunch of other repositories or authenticate with GitLab (which doesn't really make sense since the source is on GitHub and `pip` can install packages from git)

**Comment by elenapan** [comment]
According to [the ProtonVPN/python-proton-vpn-api-core README](https://github.com/ProtonVPN/python-proton-vpn-api-core/blob/8a4563f8ad3e6bf30225531e47a59d3fecbb3abc/README.md):

- `{GITLAB_INSTANCE}` should be set to `gitlab.protontech.ch`
- `{GROUP_ID}`should be set to `777`

The command then becomes:

```
pip config set global.index-url https://__token__:{GITLAB_TOKEN}@gitlab.protontech.ch/api/v4/groups/777/-/packages/pypi/simple
```

However, I get a few errors when trying it:

```
...
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8c4c59e0d0>, 'Connection to gitlab.protontech.ch timed out. (connect timeout=15)')': /api/v4/groups/777/-/packages/pypi/simple/proton-vpn-api-core/
INFO: pip is looking at multiple versions of proton-vpn-gtk-app to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement proton-vpn-api-core (from proton-vpn-gtk-app) (from versions: none)
ERROR: No matching distribution found for proton-vpn-api-core
```

Maybe this repo's README could be updated to include the correct information?

**Comment by calexandru2018** [comment]
So repo instructions contain are mainly of developers and internal use. Though to note that we currently don't provide support if you build the app from source, mainly because there are many dependencies that need to be in place. I'll take this info to see if we can improve the `README.md` file, thanks.

**Comment by calexandru2018** [comment]
@ranile in recent times we've drastically reduced the repos by half, so at this point you'll have to worry only to install the following packages:
1. https://github.com/ProtonVPN/python-proton-core

2. https://github.com/ProtonVPN/python-proton-keyring-linux

3. https://github.com/ProtonVPN/python-proton-vpn-local-agent

4. https://github.com/ProtonVPN/python-proton-vpn-api-core

5. https://github.com/ProtonVPN/python-proton-vpn-network-manager

6. https://github.com/ProtonVPN/proton-vpn-gtk-app

For now this is what we'll keep, we don't plan to reduce it too much in the near future. Closing the ticket.
