### ISSUE TITLE
Will there be a patch for Novel attack

### ISSUE THREAD

**Issue by github2099** [ProtonVPN/proton-vpn-gtk-app#51]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [X] This is not a report about my app not working as expected

----------------------------------------

https://arstechnica.com/security/2024/05/novel-attack-against-virtually-all-vpn-apps-neuters-their-entire-purpose/

Will this app be updated? 
what about the legacy https://github.com/ProtonVPN/linux-cli and https://github.com/ProtonVPN/linux-app ?

**Comment by Anonymous941** [comment]
According to that article you linked:

> The researchers believe it affects all VPN applications when they’re connected to a hostile network and that there are no ways to prevent such attacks **except when the user's VPN runs on Linux or Android**

(emphasis mine)

I personally don't know anything about this attack, so correct me if I'm wrong
