### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by tired-creating-those-usernames** [ProtonVPN/proton-vpn-gtk-app#56]
Hi,
clicking the GUI app loads few seconds ant nothing happens.
CLI:
─>‎ protonvpn-app
Traceback (most recent call last):
File "/usr/bin/protonvpn-app", line 33, in
sys.exit(load_entry_point('proton-vpn-gtk-app==4.3.2', 'console_scripts', 'protonvpn-app')())
File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/main.py", line 34, in main
controller = Controller.get(executor)
File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 59, in get
executor.submit(controller.initialize_vpn_connector).result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
self._connector = await self._api.get_vpn_connector()
File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 57, in get_vpn_connector
settings = await self.load_settings()
File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 68, in load_settings
user_tier = self._session_holder.session.vpn_account.max_tier
AttributeError: 'NoneType' object has no attribute 'max_tier'

I'm not a programmer, what is going on here?
Ubuntu with plasma

**Comment by Anonymous941** [comment]
I had a similar issue, it was because the settings were corrupted, so I removed them:

```plain
rm -rf ~/.config/Proton
rm -rf ~/.cache/Proton
```

Make sure to close the app before running these, afterwards open it and sign in again

Hope this helps!

**Comment by tired-creating-those-usernames** [comment]
> I had a similar issue, it was because the settings were corrupted, so I removed them:
> 
> ```
> rm -rf ~/.config/Proton
> rm -rf ~/.cache/Proton
> ```
> 
> Make sure to close the app before running these, afterwards open it and sign in again
> 
> Hope this helps!

unfortunately does not help...

**Comment by Anonymous941** [comment]
It seems that somehow it's not resetting.  Try closing the app, then running:

```bash
rm -rf ~/.config/Proton
rm -rf ~/.cache/Proton
rm -rf ~/.config/protonvpn
rm -rf ~/.cache/protonvpn
sudo apt purge --autoremove protonvpn # don't worry if this fails
sudo apt purge --autoremove proton-vpn-gnome-desktop
```

Then reboot.  After rebooting, reinstall the app:
```bash
wget https://repo.protonvpn.com/debian/dists/unstable/main/binary-all/protonvpn-beta-release_1.0.3-3_all.deb
sudo dpkg -i ./protonvpn-beta-release_1.0.3-3_all.deb
sudo apt update
sudo apt upgrade
sudo apt install proton-vpn-gnome-desktop
```

Hopefully this will fix it

**Comment by RagglenLove** [comment]
I'm experiencing the same thing.

```
~/.config/Proton
~/.cache/Proton
~/.config/protonvpn
~/.cache/protonvpn
```

However, these don't exist on my system. My system is Xubuntu 24.04.

**Comment by tired-creating-those-usernames** [comment]
> I'm experiencing the same thing. I'm running the flatpak version.
> 
> ```
> flatpak run com.protonvpn.www
> Traceback (most recent call last):
>   File "/app/bin/protonvpn-app", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
>     controller = Controller.get(executor)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 59, in get
>     executor.submit(controller.initialize_vpn_connector).result()
>   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
>     raise self._exception
>   File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
>     self._connector = await self._api.get_vpn_connector()
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/lib/python3.11/site-packages/proton/vpn/core/api.py", line 57, in get_vpn_connector
>     settings = await self.load_settings()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/lib/python3.11/site-packages/proton/vpn/core/api.py", line 68, in load_settings
>     user_tier = self._session_holder.session.vpn_account.max_tier
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'max_tier'
> ```
> 
> However, these file paths don't exist on my system, so I can't follow your instructions.
> 
> ```
> ~/.config/Proton
> ~/.cache/Proton
> ~/.config/protonvpn
> ~/.cache/protonvpn
> ```
> 
> My system is Xubuntu 24.04.

well I tuly hope developer or someone that understands this python shizzle wizzle will eventually come and explain us what the heck is going on here and WHAT TO DO

**Comment by tired-creating-those-usernames** [comment]
> It seems that somehow it's not resetting. Try closing the app, then running:
> 
> ```shell
> rm -rf ~/.config/Proton
> rm -rf ~/.cache/Proton
> rm -rf ~/.config/protonvpn
> rm -rf ~/.cache/protonvpn
> sudo apt purge --autoremove protonvpn # don't worry if this fails
> sudo apt purge --autoremove proton-vpn-gnome-desktop
> ```
> 
> Then reboot. After rebooting, reinstall the app:
> 
> ```shell
> wget https://repo.protonvpn.com/debian/dists/unstable/main/binary-all/protonvpn-beta-release_1.0.3-3_all.deb
> sudo dpkg -i ./protonvpn-beta-release_1.0.3-3_all.deb
> sudo apt update
> sudo apt upgrade
> sudo apt install proton-vpn-gnome-desktop
> ```
> 
> Hopefully it will work after that

this was the first thing I did after the problem occurred. these instructions are basically the same thing from the Proton site's install/uninstall procedure.

**Comment by Anonymous941** [comment]
@RagglenLove @tired-creating-those-usernames

> I'm running the flatpak version.

Sorry to waste your time, I forgot there was a Flatpak version.  :facepalm:   It makes sense why everything is failing...

```plain
flatpak uninstall --delete-data com.protonvpn.www
rm -rf ~/.var/app/com.protonvpn.www
mv ~/.local/share/keyrings ~/.local/share/keyrings.bak # this might cause other apps to forget a password or two
# maybe reboot?
```

After that, you can reinstall it:

```plain
flatpak install com.protonvpn.www
```

Again, I'm sorry about that, I never used the Flatpak version so I forgot that existed

**Comment by calexandru2018** [comment]
Hey @tired-creating-those-usernames , we'll be pushing in a couple of weeks a fix for this to beta, feel free to switch to beta whenever you want to be sure that you get the fix as soon as we release it.

**Comment by tired-creating-those-usernames** [comment]
> Hey @tired-creating-those-usernames , we'll be pushing in a couple of weeks a fix for this to beta, feel free to switch to beta whenever you want to be sure that you get the fix as soon as we release it.

I'll be the one of the tirst ones who tries it 🙂💪
Is there a way to be notified the fix arrived?

**Comment by paveltrojka** [comment]
FEDORA 40 / ProtonVPN 4.3.3 (rpm)

2024-07-22T22:03:32.134949 | proton.vpn.connection.vpnconnector:238 | INFO | CONN:STATE_CHANGED | Disconnected (initial state)
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.3.3', 'console_scripts', 'protonvpn-app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proton/vpn/app/gtk/controller.py", line 59, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
TimeoutError


Would be somehow feasible to run PROTONVPN in venv environment for greater stability ?

**Comment by calexandru2018** [comment]
Should be in beta today, just make sure you follow the beta install instructions [here](https://protonvpn.com/support/linux-prerelease/) and update from time to time to see when you can install them.

**Comment by tired-creating-those-usernames** [comment]
> Should be in beta today, just make sure you follow the beta install instructions [here](https://protonvpn.com/support/linux-prerelease/) and update from time to time to see when you can install them.

I see it is still 1.0.3-3 version added 17 of march. Is that it?
Using cli for now and wanna be sure uninstall-install-uninstall-install maneuver could be avoided in case this isn't the fixed version

**Comment by calexandru2018** [comment]
You shouldn't be looking at either the release package or meta-package as those are rarely updated, unless we need to update repo URLs, repo keys or dependencies for the app.

**Comment by tired-creating-those-usernames** [comment]
> You shouldn't be looking at either the release package or meta-package as those are rarely updated, unless we need to update repo URLs, repo keys or dependencies for the app.

installed. nothing happens.
cli:
protonvpn-app         
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.4.2', 'console_scripts', 'protonvpn-app')())
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 61, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
    self._connector = await self._api.get_vpn_connector()
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 63, in get_vpn_connector
    settings = await self.load_settings()
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 80, in load_settings
    user_tier = self._session_holder.session.vpn_account.max_tier
AttributeError: 'NoneType' object has no attribute 'max_tier'

**Comment by calexandru2018** [comment]
@tired-creating-those-usernames please do a logout/login and let me know if the issue persists please.

**Comment by tired-creating-those-usernames** [comment]
> @tired-creating-those-usernames please do a logout/login and let me know if the issue persists please.
> 
> edit: Also ensure that no packages need to be updated.
logged out
purged cli app
installed beta 
same nothing happens with UI, same error in terminal.

**Comment by tired-creating-those-usernames** [comment]
updated.
logged out
purged cli app
installed beta
same nothing happens with UI, same error in terminal.
> @tired-creating-those-usernames please do a logout/login and let me know if the issue persists please.
> 
> edit: Also ensure that no packages need to be updated.

**Comment by tired-creating-those-usernames** [comment]
Yesterday decided to take another chance and install gui. Success! 
Only weird thing  is a question mark on wifi icon, when killswitch is enabled 🤷🏻‍♂️

Edit

Question mark appears on Wireguard protocol only.

**Comment by Anonymous941** [comment]
> Question mark appears on Wireguard protocol only.

I have the exact same thing happen on all my computers, so ig it's a minor bug

**Comment by calexandru2018** [comment]
This should be fixed by now, we we've released a fix about 2 weeks ago, can you confirm this please ?

**Comment by tired-creating-those-usernames** [comment]
> This should be fixed by now, we we've released a fix about 2 weeks ago, can you confirm this please ?

which one?
the icon, or the app misbehavin?

**Comment by calexandru2018** [comment]
@tired-creating-those-usernames the `AttributeError: 'NoneType' object has no attribute 'max_tier'` bug.

> Only weird thing is a question mark on wifi icon, when killswitch is enabled

I suspect you're running a distro that does not contain the gnome version that fixes that IIRC. That is a matter of distro/DE and if it contains latest gnome or not that fixes the UI part, unfortunately we can't do much about it.

**Comment by tired-creating-those-usernames** [comment]
I am glad it is working in gui, not cli mode ant that is already satisfying

**Comment by calexandru2018** [comment]
I guess we can close the ticket then ?

**Comment by tired-creating-those-usernames** [comment]
> I guess we can close the ticket then ?

Ah! I completely forgot about that, would have done that already two months ago 🙂
