### ISSUE TITLE
Tags are being removed frequently

### ISSUE THREAD

**Issue by molaeiali** [ProtonVPN/proton-vpn-gtk-app#6]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

As an AUR maintainer I'm using tags here, and they are being created removed randomly, can I rely on them or not?

**Comment by WolfangAukang** [comment]
Same for NixOS. We are trying to package the new version and the deletion of tags for `proton-core` and `proton-vpn-logger` is affecting the process.

**Comment by SebTM** [comment]
https://github.com/ProtonVPN/python-proton-vpn-api-core/issues/1

This issue currently holds the main conversation with official responses from the vpn-team.

**Comment by calexandru2018** [comment]
We've managed to fix this, whenever we'll push a new version, a tag we'll be created and synced to github :)

**Comment by calexandru2018** [comment]
Tags have been pushed to all projects and will be getting new tags as we release new versions, thank you all for your patience :)
