### ISSUE TITLE
UPI payments for Proton VPN are not working on my phone 

### ISSUE THREAD

**Issue by Souchikjoardar1** [ProtonVPN/proton-vpn-gtk-app#61]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ ] upi payments are not working for my version of the proton vpn app on my phone android 12 device .
- [ ] payments of other types and UPI payments on other devices are working fine with the same email id as mine but it just doesn't work on my personal device 

----------------------------------------

**Comment by calexandru2018** [comment]
@Souchikjoardar1 how is this related to the gtk app ?
