### ISSUE TITLE
Autostart Protonvpn-app, with hidden GUI Window?

### ISSUE THREAD

**Issue by DarkDk123** [ProtonVPN/proton-vpn-gtk-app#62]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [✅ ] I have searched open and closed issues for duplicates
- [ ❌] This isn't a feature request
- [ ✅] This is not a report about my app not working as expected

----------------------------------------
I just want to know if there is any way to start protonvpn-linux **minimized** at startup? i want only the  **Tray icon** on startup, and do not want to close the GUI every time i start my system!

**Comment by Anonymous941** [comment]
This was fixed in #58

**Comment by DarkDk123** [comment]
Yeah, got it!
