### ISSUE TITLE
setup issue: remote: Not Found

### ISSUE THREAD

**Issue by hedgehogdrfrink** [ProtonVPN/proton-vpn-gtk-app#65]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [ x] I have searched open and closed issues for duplicates
- [ x] This isn't a feature request
- [ x] This is not a report about my app not working as expected

----------------------------------------

Following readme guide and seeing the following issue within terminal on linux,

```shell
git submodule update --init --recursive
Cloning into '/home/user/Downloads/proton-vpn-gtk-app/scripts/devtools'...
remote: Not Found
fatal: repository 'https://github.com/ProtonVPN/integration/devtools.git/' not found
fatal: clone of 'https://github.com/ProtonVPN/integration/devtools.git' into submodule path '/home/user/Downloads/proton-vpn-gtk-app/scripts/devtools' failed
Failed to clone 'scripts/devtools'. Retry scheduled
Cloning into '/home/user/Downloads/proton-vpn-gtk-app/scripts/devtools'...
remote: Not Found
fatal: repository 'https://github.com/ProtonVPN/integration/devtools.git/' not found
fatal: clone of 'https://github.com/ProtonVPN/integration/devtools.git' into submodule path '/home/user/Downloads/proton-vpn-gtk-app/scripts/devtools' failed
Failed to clone 'scripts/devtools' a second time, aborting
``` 

Not sure how to resolve this issue

**Comment by calexandru2018** [comment]
That is guidelines for us to install internal tools, feel free to skip it.

**Comment by xandark** [comment]
Could the [Virtual environment documentation](https://github.com/ProtonVPN/proton-vpn-gtk-app#virtual-environment) on the README page be updated so that it makes sense to be installed? What do we do about `replacing {GITLAB_TOKEN}`? This is github. Also, the requirements.txt file contains only `-e ".[development]"` and where are the Python packages???
