### ISSUE TITLE
Binaries and AppImage please

### ISSUE THREAD

**Issue by YALdysse** [ProtonVPN/proton-vpn-gtk-app#72]
Please add builds (binaries) to the “Releases” section. This will make it easier for users to download the program.
It would also be great if you could make a package of the program in AppImage format. In this case, ProtonVPN will be able to run on many Linux distributions. The AppImage version is sorely lacking.

**Comment by github2099** [comment]
or flatpak 
edit: there is a flatpak in flathub but not official

**Comment by github2099** [comment]
good new, @calexandru2018 is working on making it official
https://github.com/flathub/com.protonvpn.www/issues/349

**Comment by calexandru2018** [comment]
We won't be adding binaries nor appimage, at most we could work on flatpak, that but that will take some time. Closing the ticket.
