### ISSUE TITLE
Wireguard not being selected

### ISSUE THREAD

**Issue by molaeiali** [ProtonVPN/proton-vpn-gtk-app#73]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected
----------------------------------------
As you can see here, code is calling `self._api.fetch_certificate()`:

https://github.com/ProtonVPN/proton-vpn-gtk-app/blob/9d77c58322fdae2a1ef925b200c524afbec39d1a/proton/vpn/app/gtk/controller.py#L368

And I can't see a `fetch_certificate` function here:

https://github.com/ProtonVPN/python-proton-vpn-api-core/blob/58a90f43517e7d84289e2aa925146ca26cd06d19/proton/vpn/core/api.py#L40

So this is causing this error each time I select Wireguard as protocol:
```
proton.vpn.app.gtk.utils.exception_handler:190 | CRITICAL | APP:CRASH | Unexpected error.
Traceback (most recent call last):
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/site-packages/proton/vpn/app/gtk/controller.py", line 368, in save_and_update
    await self._api.fetch_certificate()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProtonVPNAPI' object has no attribute 'fetch_certificate'
```

**Comment by calexandru2018** [comment]
Hey @molaeiali, thanks for the report. We've missed that during a recent refactor, though it has already been fixed and it should land in beta next week. Thanks for raising it 👍

**Comment by calexandru2018** [comment]
@molaeiali this is already fixed, feel free to close the ticket.
