### ISSUE TITLE
Option to 'Start app minimized' doesn't work

### ISSUE THREAD

**Issue by xcpn** [ProtonVPN/proton-vpn-gtk-app#76]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [X] This is not a report about my app not working as expected

----------------------------------------
I don't know if there is something I'm doing wrong or a problem with the app, but enabling the option to 'Start app minimized' does absolutely nothing.

If I quit the app and reopen it or if I reboot the system, the app window still launches. I also tried launching using the terminal with `protonvpn-app --start-minimized` and results to the same thing.

Here is some info:

- Debian 11 (Stable)
- Linux 5.10.0-33-amd64
- GNOME 3.38.5 (Wayland)
- ProtonVPN v4.7.1

The app is set as a startup application and the 'Ubuntu appindicator' extension is installed because I only use the VPN using the trey icon. The option to start minimized is enabled and a server to auto-connect on launch is set.

**Comment by Cherkah** [comment]
i confirme on archlinux also

**Comment by Red6785** [comment]
Confirmed here, too.

**Comment by calexandru2018** [comment]
Hey all, thank you for your feedback. We've also confirmed this and it seems we've introduced a regression recently. Should be fixed in the next beta, thank you all!

**Comment by calexandru2018** [comment]
Fix has been released on beta, please give it a try there.

**Comment by xcpn** [comment]
Hey @calexandru2018, I only use Stable. When will it hit the release to test?

Thanks for the fast fix.

**Comment by calexandru2018** [comment]
@xcpn it should be out within a week or so.

**Comment by fthx** [comment]
v. 4.7.2 start minimized option works.
But once the app is started minimized, I have no way to make the gtk window appear using the GNOME dash launcher.
I can do it using Ubuntu AppIndicators VPN icon.

**Comment by calexandru2018** [comment]
@fthx the idea was to only display it via the app indicator. What you're asking for is by clicking on the ProtonVPN icon, it should displayed ?

**Comment by fthx** [comment]
Yes that's what I mean.

Not displaying app at startup is very convenient. But after that I have often to access Proton VPN to cancel connection for another VPN, well I have to display its window. That's not annoying for those who want the app to be permanently hidden: they just have to not click on its icon!  ^_^

And (as I wrote once), Ubuntu AppIndicators is a questionable extension (huge code, some bugs, power usage...).
(I still can write a simple companion extension if there are now simple command line options.)

**Comment by calexandru2018** [comment]
Hey @xcpn the issue should be fixed. @fthx i'll take your idea for consideration with the team, please feel free to close the ticket

**Comment by xcpn** [comment]
@calexandru2018 thanks for letting me know Alexandru, already upgraded as soon as the patch came through.

Also, I must say this version upgraded the overall speed of the app substantially. The app literally launches and auto-connects to a server 3 times faster than before for me.

**Comment by calexandru2018** [comment]
@xcpn indeed, we've worked to improve the app performance. As we're growing in server numbers the apps we're getting sluggish in generating hundreds of thousands of servers. We noted also that the app was eating up around 350Mb of RAM at startup, which we thought it was a lot, not to talk about the overall slowness and app only loading 3-5 seconds after clicking on it.
We managed to downsize the initial app start-up to 75Mb and refactored the search widget, which allowed us to start the app withing 1sec or so.

**Comment by CodingKoalaGeneral** [comment]
fyi

having the 'Start app minimized' set using Gnome without an extension for indicator support renders the app unusable.
Starting the app via the .desktop entry should show the application, currently it in that scenario nothing happens.

**Comment by fthx** [comment]
I recently read a (quite old) GNOME guideline that recommends not relying on an extension without checking if available.

Related: I upgraded/updated the Proton VPN GNOME extension but did not find a way to make the gtk app appear if minimized on startup (a dbus trick?).

Of course, I can add some code to close the gtk app window on startup after its creation, but that's just a hack not really clean. ;-)

**Comment by Enigmatyxx** [comment]
@fthx Yes, this is what I ended up doing here: https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/140

I use xdotool to accomplish what you suggested. And yes, it's hacky:

`protonvpn-app --start-minimized & sleep 2 && xdotool search --sync --class "protonvpn-app" windowunmap`

**Comment by fthx** [comment]
ok thanks!
Fyi the vpn app now relies on the appindicator extension, not ayatana anymore, to check the availability of minimize-to-tray.
I reported this, I don't remember how (app or github).

**Comment by Enigmatyxx** [comment]
@fthx Thanks for the heads up! And for anyone who's looking for a hacky .desktop launcher script to fix this, I included two at https://github.com/ProtonVPN/proton-vpn-gtk-app/issues/140:

One for a simple window close, and the other based on https://github.com/MacBeibhinn/LinuxScripts/blob/main/ProtonVPN/start_protonvpn_minimized.sh, that waits until a connection is established before closing. I prefer to have a very blatant indication if I log in and my internet is down.
