### ISSUE TITLE
Wrong StartupWMClass `Protonvpn`, should be `protonvpn-app`

### ISSUE THREAD

**Issue by antermin** [ProtonVPN/proton-vpn-gtk-app#9]
https://github.com/ProtonVPN/proton-vpn-gtk-app/blob/713324e9e4ee9f030c8115072cae379eb3340c42/rpmbuild/SOURCES/protonvpn-app.desktop#L7

Originally reported by @sbeve72 in [this AUR comment](https://aur.archlinux.org/packages/proton-vpn-gtk-app#comment-943379).

**Comment by calexandru2018** [comment]
True indeed, thank you. Once this fix gets released we'll close the ticket, thank you.

**Comment by calexandru2018** [comment]
Hey @antermin apologize for the long time it took us to fix this. It has been fixed internally, once we release this to stable I'll close the ticket. Thank you.

**Comment by calexandru2018** [comment]
hey @antermin , thanks again and this has been fixed [here](https://github.com/ProtonVPN/proton-vpn-gtk-app/commit/df8323aafcd72c0d3e7d87bbea7a5020cda6fb97), I'll be closing the ticket.
